Update UDQ Mark WCONHIST, WINJFCNC and WSEGVALV as supporting UDAs
OPM/opm-reference-manual pull request #405
Opened 2024-10-11 09:46 UTC by gdfldm

2024-11-04 20:00 UTC, blattms requested changes
Please feel free to disagree with my arguments. Those might due to me not being a native speaker.

2024-11-04 21:55 UTC, gdfldm commented on parts/chapters/subsections/12.3/UDQ.fodt
> +         <text:p text:style-name="P19300">ASSIGN: Assigns a constant numerical value to the VARIABLE and sets the UPDATE status to OFF.</text:p>
I have suggested some updates to the text to make it clearer that a value is being assigned to the UDQ rather than VARIABLE.

2024-11-05 08:51 UTC, blattms commented on parts/chapters/subsections/12.3/UDQ.fodt
> +         <text:p text:style-name="P19302">DEFINE: EXPRESSSION should be a mathematical expression. Allowable tokens for the expression are SUMMARY or UDQ variables, real numbers (can be integers or s
There is one "S" to many.

2024-11-05 11:01 UTC, blattms commented
Cool. Thanks a lot.

2024-11-05 11:02 UTC, merged