Update CNAMES keyword
OPM/opm-reference-manual pull request #449
Opened 2024-12-23 16:11 UTC by gdfldm

Three components H20, CO2 and NACL are now required if used with the CO2STORE model

2025-01-03 18:36 UTC, blattms commented on parts/chapters/subsections/8.3/CNAMES.fodt
> +        <text:p text:style-name="P10195">This keyword is only supported by OPM Flow when the two phase gas-water CO<text:span text:style-name="T999">2</text:span> storage model has been activated usi
I might be misunderstanding this.

To me it sounds like I have provide all three of those all the time, but it seems like I need to select only NCOMPS components from this set (H2O, CO2, NACL). At least there are cases in opm-tests/co2store that only use 2 (e.g. CO2STORE_GASWAT).

The new example below runs, but I would hope that the old version does, too.

2025-01-03 18:42 UTC, gdfldm commented on parts/chapters/subsections/8.3/CNAMES.fodt
> +        <text:p text:style-name="P10195">This keyword is only supported by OPM Flow when the two phase gas-water CO<text:span text:style-name="T999">2</text:span> storage model has been activated usi
As I understand it you need to specify H2O, CO2, NACL in order for the DENAQA and VISCAQA know which order the Erzokhi parameters are given in the tables.

2025-01-03 18:59 UTC, gdfldm commented on parts/chapters/subsections/8.3/CNAMES.fodt
> +        <text:p text:style-name="P10195">This keyword is only supported by OPM Flow when the two phase gas-water CO<text:span text:style-name="T999">2</text:span> storage model has been activated usi
I will check and update the text.

2025-01-07 13:34 UTC, blattms requested changes

2025-01-07 13:34 UTC, blattms commented on parts/chapters/subsections/8.3/CNAMES.fodt
> +        <text:p text:style-name="P10195">This keyword is only supported by OPM Flow when the two phase gas-water CO<text:span text:style-name="T999">2</text:span> storage model has been activated usi
Sorry to bother you again. What is up with the ` Copy 1 Copy 1 Copy1` in the href? Is it supposed to be like this?

2025-01-07 13:56 UTC, gdfldm commented on parts/chapters/subsections/8.3/CNAMES.fodt
> +        <text:p text:style-name="P10195">This keyword is only supported by OPM Flow when the two phase gas-water CO<text:span text:style-name="T999">2</text:span> storage model has been activated usi
No problem. All feedback is appreciated :).
I think these are created when a bookmark is copied and pasted in LibreOffice.
I will try and replace it with something better.

2025-01-07 14:07 UTC, gdfldm commented on parts/chapters/subsections/8.3/CNAMES.fodt
> +        <text:p text:style-name="P10195">This keyword is only supported by OPM Flow when the two phase gas-water CO<text:span text:style-name="T999">2</text:span> storage model has been activated usi
Changed to:
REF_HEADING_KEYWORD_CNAMES_8_3

2025-01-07 14:27 UTC, gdfldm commented on parts/chapters/subsections/8.3/CNAMES.fodt
> +        <text:p text:style-name="P10195">This keyword is only supported by OPM Flow when the two phase gas-water CO<text:span text:style-name="T999">2</text:span> storage model has been activated usi
> have more those

I have found about 18 keywords and 15 headings that are similar.

2025-01-07 14:30 UTC, blattms commented on parts/chapters/subsections/8.3/CNAMES.fodt
> +        <text:p text:style-name="P10195">This keyword is only supported by OPM Flow when the two phase gas-water CO<text:span text:style-name="T999">2</text:span> storage model has been activated usi
And no it turns out that my comment was bad and might have made things worse:

Indeed those bookmarks are from the original document.They first appeared in 3b1160e46c0d. Hence maybe it is safer to leave them as they are and revert/remove the last commit?

Sorry again...

2025-01-07 15:03 UTC, blattms commented on parts/chapters/subsections/8.3/CNAMES.fodt
> +        <text:p text:style-name="P10195">This keyword is only supported by OPM Flow when the two phase gas-water CO<text:span text:style-name="T999">2</text:span> storage model has been activated usi
> But it does seem to be taking longer to do Tools>Update>Update All in LibreOffice?

Probably that changes it again, because it does not adhere to what libreoffice expects?

2025-01-08 12:49 UTC, blattms approved these changes

2025-01-08 12:49 UTC, merged